import { StyleSheet } from "react-native"

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    backgroundColor: "#fff",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
  },
  placeholder: {
    width: 40,
  },
  connectionStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 8,
  },
  disconnectedStatus: {
    backgroundColor: "#f8d7da",
    iconColor: "#721c24",
    textColor: "#721c24",
  },
  reconnectingStatus: {
    backgroundColor: "#fff3cd",
    iconColor: "#856404",
    textColor: "#856404",
  },
  fcmStatus: {
    backgroundColor: "#d1e7dd",
    iconColor: "#0f5132",
    textColor: "#0f5132",
  },
  connectionStatusText: {
    fontSize: 12,
    marginLeft: 8,
    fontWeight: "500",
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 24,
  },
  mapContainer: {
    height: 300,
    margin: 16,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  initialLoadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  initialLoadingAnimation: {
    width: 150,
    height: 150,
  },
  initialLoadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#4b5563",
    textAlign: "center",
  },
  loaderContainer: {
    margin: 16,
    padding: 24,
    borderRadius: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  iconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#e0f2fe",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  lottieAnimation: {
    width: 120,
    height: 120,
  },
  loaderTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e40af",
    marginBottom: 8,
    textAlign: "center",
  },
  loaderMessage: {
    fontSize: 14,
    color: "#4b5563",
    textAlign: "center",
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  timerContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 16,
  },
  timerText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#4b5563",
    fontWeight: "500",
  },
  fcmNotice: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#d1e7dd",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    marginBottom: 16,
  },
  fcmNoticeText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#0f5132",
    fontWeight: "500",
  },
  stepIndicatorContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 24,
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#d1d5db",
    marginHorizontal: 4,
  },
  stepDotActive: {
    backgroundColor: "#E3838D",
    width: 24,
  },
  cancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: "#fee2e2",
  },
  cancelButtonText: {
    color: "#dc2626",
    fontWeight: "600",
    fontSize: 14,
  },
  rideDetailsCard: {
    margin: 16,
    padding: 16,
    borderRadius: 12,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  estimatedTime: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
  },
  estimatedTimeText: {
    marginLeft: 4,
    fontSize: 12,
    color: "#059669",
    fontWeight: "600",
  },
  rideInfo: {
    marginBottom: 16,
  },
  rideInfoItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  rideInfoText: {
    marginLeft: 12,
    flex: 1,
  },
  rideInfoLabel: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 2,
  },
  rideInfoValue: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "500",
  },
  locationConnector: {
    marginLeft: 12,
    paddingLeft: 12,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  locationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#9ca3af",
  },
  locationLine: {
    width: 2,
    height: 20,
    backgroundColor: "#9ca3af",
  },
  divider: {
    height: 1,
    backgroundColor: "#e5e7eb",
    marginBottom: 16,
  },
  fareDetails: {
    paddingTop: 8,
  },
  fareTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 12,
  },
  fareItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  fareItemText: {
    fontSize: 14,
    color: "#4b5563",
  },
  fareItemValue: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "500",
  },
  fareTotal: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  totalText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
  },
  totalAmount: {
    fontSize: 18,
    fontWeight: "700",
    color: "#de4051",
  },
  fareNote: {
    marginTop: 12,
    padding: 12,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
  },
  fareNoteText: {
    fontSize: 12,
    color: "#4b5563",
    lineHeight: 18,
  },
  noteHighlight: {
    fontWeight: "600",
    color: "#111827",
  },
  loadingFare: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  loadingFareText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#4b5563",
  },
  bottomContainer: {
    padding: 16,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  paymentMethod: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  paymentText: {
    marginLeft: 8,
    fontSize: 14,
    color: "#111827",
    fontWeight: "500",
    flex: 1,
  },
  changeText: {
    fontSize: 14,
    color: "#E3838D",
    fontWeight: "600",
  },
  confirmButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#000",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  confirmButtonDisabled: {
    backgroundColor: "#93c5fd",
    opacity: 0.8,
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  confirmButtonPrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  errorContainer: {
    position: "absolute",
    bottom: 90,
    left: 16,
    right: 16,
    backgroundColor: "#fee2e2",
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  errorText: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: "#b91c1c",
  },
  successContainer: {
    position: "absolute",
    bottom: 90,
    left: 16,
    right: 16,
    backgroundColor: "#d1e7dd",
    borderRadius: 8,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  successText: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: "#0f5132",
  },
  dismissButton: {
    padding: 4,
  },
  reconnectingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  reconnectingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
})
