import { StyleSheet, Platform, Dimensions } from "react-native"

const { width } = Dimensions.get("window")
const isIOS = Platform.OS === "ios"

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  header: {

    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom:2,
    paddingVertical: 36,
    backgroundColor: "#FF5252",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerRight: {
    width: 40,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  restaurantContainer: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: 12,
    marginHorizontal: 12,
    marginTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  restaurantInfo: {
    flex: 1,
  },
  restaurantName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333333",
    marginBottom: 4,
  },
  restaurantAddress: {
    fontSize: 14,
    color: "#666666",
  },
  deliveryTimeContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F0F0",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  deliveryTimeText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#666666",
    marginLeft: 4,
  },
  sectionTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333333",
    marginLeft: 8,
    flex: 1,
  },
  itemCount: {
    fontSize: 14,
    color: "#666666",
  },
  cartContainer: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 8,
    borderRadius: 12,
    marginHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  cartItem: {
    flexDirection: "row",
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  foodImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginRight: 12,
  },
  foodInfo: {
    flex: 1,
    justifyContent: "center",
  },
  foodName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 4,
  },
  foodDescription: {
    fontSize: 13,
    color: "#666666",
    marginBottom: 6,
  },
  foodPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: "#333333",
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#FF5252",
    borderRadius: 20,
    padding: 4,
  },
  quantityButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FF5252",
    justifyContent: "center",
    alignItems: "center",
  },
  quantityText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginHorizontal: 10,
  },
  addressContainer: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 8,
    borderRadius: 12,
    marginHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  changeButton: {
    paddingHorizontal: 10,
  },
  changeText: {
    color: "#FF5252",
    fontSize: 14,
    fontWeight: "600",
  },
  addressContent: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  addressDetails: {
    flex: 1,
  },
  addressTypeContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  addressType: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginRight: 8,
  },
  defaultBadge: {
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  defaultBadgeText: {
    fontSize: 12,
    color: "#4CAF50",
    fontWeight: "500",
  },
  addressText: {
    fontSize: 14,
    color: "#666666",
    lineHeight: 20,
  },
  editAddressButton: {
    padding: 8,
  },
  addAddressButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF5252",
    paddingVertical: 12,
    borderRadius: 8,
  },
  addAddressText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  couponsContainer: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 8,
    borderRadius: 12,
    marginHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  couponsScrollContainer: {
    paddingBottom: 8,
  },
  couponLoadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  couponLoadingText: {
    marginLeft: 10,
    fontSize: 14,
    color: "#666666",
  },
  couponErrorContainer: {
    alignItems: "center",
    padding: 20,
  },
  couponErrorText: {
    marginTop: 8,
    fontSize: 14,
    color: "#FF5252",
    textAlign: "center",
    marginBottom: 12,
  },
  retryButton: {
    backgroundColor: "#FF5252",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 4,
  },
  retryButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
  },
  noCouponsContainer: {
    alignItems: "center",
    padding: 20,
  },
  noCouponsText: {
    marginTop: 8,
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
  },
  couponItem: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    padding: 12,
    marginRight: 12,
    width: 180,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    position: "relative",
  },
  selectedCoupon: {
    borderColor: "#FF5252",
    borderWidth: 2,
    backgroundColor: "#FFF8F8",
  },
  disabledCoupon: {
    opacity: 0.7,
  },
  couponHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  couponTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333333",
    marginLeft: 6,
    flex: 1,
  },
  selectedCouponText: {
    color: "#FF5252",
  },
  couponBadge: {
    backgroundColor: "#F0F0F0",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    marginBottom: 8,
  },
  selectedCouponBadge: {
    backgroundColor: "#FFE8E8",
  },
  couponCode: {
    fontSize: 14,
    fontWeight: "700",
    color: "#333333",
    textAlign: "center",
  },
  selectedCouponCodeText: {
    color: "#FF5252",
  },
  couponDetails: {
    marginTop: 4,
  },
  couponDetailText: {
    fontSize: 12,
    color: "#666666",
    marginBottom: 2,
  },
  couponMinOrder: {
    fontSize: 12,
    color: "#666666",
    marginTop: 4,
  },
  couponMinOrderHighlight: {
    color: "#FF5252",
    fontWeight: "500",
  },
  appliedTag: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: "#FF5252",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderBottomLeftRadius: 8,
  },
  appliedTagText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
  },
  paymentMethodsContainer: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 8,
    borderRadius: 12,
    marginHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  paymentMethod: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#EEEEEE",
    borderRadius: 8,
    marginBottom: 12,
    paddingHorizontal: 12,
  },
  selectedPayment: {
    borderColor: "#FF5252",
    backgroundColor: "#FFF8F8",
  },
  paymentMethodContent: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  paymentIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F0F0F0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  selectedPaymentIconContainer: {
    backgroundColor: "#FF5252",
  },
  paymentMethodInfo: {
    flex: 1,
  },
  paymentMethodName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 4,
  },
  selectedPaymentText: {
    color: "#FF5252",
  },
  paymentMethodDescription: {
    fontSize: 13,
    color: "#666666",
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#CCCCCC",
    justifyContent: "center",
    alignItems: "center",
  },
  radioButtonSelected: {
    borderColor: "#FF5252",
  },
  radioButtonInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FF5252",
  },
  billDetailsContainer: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    marginBottom: 8,
    borderRadius: 12,
    marginHorizontal: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  billItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  billItemLabel: {
    fontSize: 14,
    color: "#666666",
  },
  billItemValue: {
    fontSize: 14,
    color: "#333333",
    fontWeight: "500",
  },
  discountText: {
    color: "#4CAF50",
    fontSize: 14,
    fontWeight: "500",
  },
  totalItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    marginTop: 4,
  },
  totalText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333333",
  },
  totalValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF5252",
  },
  savingContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5E9",
    padding: 10,
    borderRadius: 6,
    marginTop: 12,
  },
  savingText: {
    fontSize: 13,
    color: "#4CAF50",
    fontWeight: "500",
    marginLeft: 6,
  },
  checkoutButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  checkoutSummary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  checkoutTotalLabel: {
    fontSize: 12,
    color: "#666666",
    marginBottom: 4,
  },
  totalAmount: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333333",
  },
  checkoutButton: {
    backgroundColor: "#FF5252",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  disabledButton: {
    backgroundColor: "#CCCCCC",
  },
  checkoutButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    marginRight: 8,
  },
  confirmationOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  confirmationModal: {
    width: width * 0.9,
    maxHeight: "80%",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    overflow: "hidden",
  },
  confirmationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#EEEEEE",
  },
  confirmationTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333333",
  },
  confirmationContent: {
    maxHeight: 400,
  },
  confirmationSection: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  confirmationSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333333",
    marginBottom: 8,
  },
  confirmationAddress: {
    fontSize: 14,
    color: "#666666",
    lineHeight: 20,
  },
  confirmationPayment: {
    fontSize: 14,
    color: "#666666",
  },
  confirmationItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  confirmationItemName: {
    fontSize: 14,
    color: "#333333",
    flex: 1,
  },
  confirmationItemPrice: {
    fontSize: 14,
    color: "#333333",
    fontWeight: "500",
  },
  confirmationBillItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  confirmationTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
    marginTop: 8,
  },
  confirmationTotalText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333333",
  },
  confirmationTotalValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF5252",
  },
  confirmationActions: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#EEEEEE",
  },
  confirmationCancelButton: {
    flex: 1,
    padding: 16,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#EEEEEE",
  },
  confirmationCancelText: {
    fontSize: 16,
    color: "#666666",
    fontWeight: "600",
  },
  confirmationConfirmButton: {
    flex: 1,
    padding: 16,
    alignItems: "center",
    backgroundColor: "#FF5252",
  },
  confirmationConfirmText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "600",
  },
})
