
import { StyleSheet, Dimensions, Platform } from "react-native"

const { width, height } = Dimensions.get("window")

const COLORS = {
  primary: "#DC2626", // Red primary
  secondary: "#EF4444", // Light red
  success: "#22C55E", // Green for success
  warning: "#F59E0B", // Amber for warnings
  danger: "#DC2626", // Red for danger
  background: "#F9FAFB", // Light gray background
  surface: "#FFFFFF", // White surface
  text: {
    primary: "#111827", // Dark gray
    secondary: "#6B7280", // Medium gray
    light: "#9CA3AF", // Light gray
  },
  border: "#E5E7EB", // Light border
  shadow: "rgba(220, 38, 38, 0.1)", // Red shadow
}

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingBottom: Platform.OS === "ios" ? 140 : 120,
  },
  container: {
    padding: 16,
  },

  mapContainer: {
    height: Platform.OS === "ios" ? 280 : 250,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    elevation: 4,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    backgroundColor: COLORS.surface,
  },
  map: {
    flex: 1,
  },
  mapOverlay: {
    position: "absolute",
    top: 16,
    right: 16,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 12,
    padding: 12,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  routeInfo: {
    alignItems: "center",
  },
  routeDistance: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.primary,
    marginBottom: 2,
  },
  routeDuration: {
    fontSize: 12,
    color: COLORS.text.secondary,
    fontWeight: "500",
  },

  // Loading States
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 48,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    marginVertical: 16,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: COLORS.text.secondary,
    textAlign: "center",
    fontWeight: "500",
  },
  retryText: {
    marginTop: 8,
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: "600",
  },

  // Error States
  errorContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 32,
    paddingHorizontal: 24,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    marginVertical: 16,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.danger,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  errorTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginTop: 12,
    marginBottom: 8,
  },
  errorText: {
    color: COLORS.text.secondary,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 16,
  },
  retryButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
    elevation: 2,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },

  // Tab Navigation
  tabContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 4,
    marginBottom: 16,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
  },
  activeTab: {
    backgroundColor: COLORS.primary,
    elevation: 2,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  tabText: {
    marginLeft: 6,
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.text.secondary,
  },
  activeTabText: {
    color: "#fff",
  },

  // Tab Content
  tabContent: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },

  // User Tab
  userCard: {
    backgroundColor: COLORS.surface,
  },
  userHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  userAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: `${COLORS.primary}15`,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginBottom: 4,
  },
  userPhone: {
    fontSize: 14,
    color: COLORS.text.secondary,
    fontWeight: "500",
  },
  callButton: {
    backgroundColor: COLORS.success,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: COLORS.success,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },

  // Address Section
  addressSection: {
    marginTop: 8,
  },
  addressItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  locationDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 4,
    marginRight: 16,
  },
  routeLine: {
    width: 2,
    height: 20,
    backgroundColor: COLORS.border,
    marginLeft: 5,
    marginBottom: 8,
  },
  addressContent: {
    flex: 1,
  },
  addressLabel: {
    fontSize: 12,
    color: COLORS.text.secondary,
    fontWeight: "600",
    textTransform: "uppercase",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  addressValue: {
    fontSize: 14,
    color: COLORS.text.primary,
    lineHeight: 20,
    fontWeight: "500",
  },

  // Ride Tab
  rideDetailsCard: {
    backgroundColor: COLORS.surface,
  },
  statusContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  statusLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text.primary,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  rideMetrics: {
    marginBottom: 24,
  },
  metricItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  metricLabel: {
    fontSize: 14,
    color: COLORS.text.secondary,
    fontWeight: "500",
    marginLeft: 12,
    flex: 1,
  },
  metricValue: {
    fontSize: 14,
    color: COLORS.text.primary,
    fontWeight: "600",
  },
  cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: `${COLORS.danger}10`,
    borderWidth: 1,
    borderColor: `${COLORS.danger}30`,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.danger,
    marginLeft: 8,
  },

  fareCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 20,
    elevation: 4,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    borderWidth: 1,
    borderColor: `${COLORS.primary}20`,
  },
  fareLabel: {
    fontSize: 17,
    fontWeight: "600",
    color: COLORS.text.primary,
    marginBottom: 12,
    textAlign: "center",
  },
  fareNoteContainer: {
    backgroundColor: `${COLORS.primary}08`,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
  },
  fareNote: {
    fontSize: 14,
    color: COLORS.text.primary,
    lineHeight: 20,
    textAlign: "center",
  },
  fareValue: {
    fontSize: 36,
    fontWeight: "900",
    color: COLORS.primary,
    textAlign: "center",
    letterSpacing: -1,
  },

  // Bottom Button
  bottomButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.surface,
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    elevation: 8,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  bottomButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  bottomButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginRight: 8,
  },

  // No Data State
  noDataContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 64,
    paddingHorizontal: 32,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    marginVertical: 16,
    elevation: 2,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  noDataTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginTop: 16,
    marginBottom: 8,
  },
  noDataText: {
    fontSize: 14,
    color: COLORS.text.secondary,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  refreshButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
  },
  refreshButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    maxHeight: height * 0.8,
    width: width * 0.9,
    maxWidth: 400,
    elevation: 8,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: COLORS.text.primary,
  },
  modalSubtitle: {
    fontSize: 16,
    color: COLORS.text.secondary,
    paddingHorizontal: 20,
    paddingVertical: 16,
    lineHeight: 22,
  },

  // Cancel Modal
  reasonsList: {
    maxHeight: height * 0.4,
  },
  reasonItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  selectedReason: {
    backgroundColor: `${COLORS.primary}10`,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: COLORS.primary,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 2,
  },
  radioSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.primary,
  },
  reasonContent: {
    flex: 1,
    marginLeft: 12,
  },
  reasonName: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.text.primary,
    marginBottom: 4,
  },
  reasonDescription: {
    fontSize: 14,
    color: COLORS.text.secondary,
    lineHeight: 18,
  },
  modalActions: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  cancelModalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    marginRight: 8,
    backgroundColor: COLORS.background,
  },
  cancelModalText: {
    fontSize: 16,
    color: COLORS.text.primary,
    fontWeight: "600",
  },
  confirmButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: COLORS.danger,
    alignItems: "center",
    marginLeft: 8,
  },
  disabledButton: {
    backgroundColor: COLORS.text.light,
  },
  confirmButtonText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },

  // OTP Modal
  otpModal: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 32,
    width: width * 0.9,
    maxWidth: 400,
    alignItems: "center",
    elevation: 8,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  otpTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginTop: 16,
    marginBottom: 8,
  },
  otpSubtitle: {
    fontSize: 14,
    color: COLORS.text.secondary,
    textAlign: "center",
    marginBottom: 32,
    lineHeight: 20,
  },
  otpInput: {
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: 16,
    padding: 20,
    fontSize: 32,
    fontWeight: "bold",
    width: "100%",
    marginBottom: 32,
    letterSpacing: 12,
    textAlign: "center",
    backgroundColor: `${COLORS.primary}05`,
  },
  otpButtons: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
  },
  otpCancelButton: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginRight: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  otpCancelText: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: "600",
  },
  otpVerifyButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginLeft: 8,
  },
  otpVerifyText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },

  // Payment Modal
  paymentModal: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 32,
    width: width * 0.9,
    maxWidth: 400,
    alignItems: "center",
    elevation: 8,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  paymentTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.text.primary,
    marginTop: 16,
    marginBottom: 8,
  },
  paymentAmount: {
    fontSize: 36,
    fontWeight: "bold",
    color: COLORS.success,
    marginBottom: 32,
  },
  paymentMethods: {
    flexDirection: "row",
    width: "100%",
    marginBottom: 24,
  },
  paymentMethod: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  activePaymentMethod: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  paymentMethodText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.text.secondary,
  },
  activePaymentMethodText: {
    color: "#fff",
  },
  qrContainer: {
    alignItems: "center",
    marginBottom: 24,
    padding: 20,
    backgroundColor: COLORS.background,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  qrImage: {
    width: 160,
    height: 160,
    borderRadius: 12,
  },
  qrText: {
    marginTop: 12,
    fontSize: 12,
    color: COLORS.text.secondary,
    textAlign: "center",
    fontWeight: "500",
  },
  paymentButtons: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
  },
  paymentCancelButton: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginRight: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  paymentCancelText: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: "600",
  },
  paymentCollectButton: {
    flex: 1,
    backgroundColor: COLORS.success,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    marginLeft: 8,
  },
  paymentCollectText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
})
